version: '3.3'
services:
  database:
    container_name: database
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - /var/folders/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - web_pacani

  backend:
    container_name: backend
    build: ./backend/
    depends_on:
      - database
    networks:
      web_pacani:
          ipv4_address: 172.20.0.10

  frontend:
    container_name: frontend
    build: ./frontend/
    depends_on:
      - backend
    networks:
      web_pacani:
          ipv4_address: 172.20.0.11
    expose:
      - "5176" #change to .env
    ports:
      - '5176:5176'

networks:
  web_pacani:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
