version: '3.3'
services:
  database:
    container_name: database
    image: postgres:13.4-buster
    expose:
      - "5432"
    volumes:
      # - /Users/namina/postgres:/data/postgres # school
      - /Users/aleksandr/postgres:/data/postgres # my mac
    env_file:
      - docker.env
    networks:
      - web_pacani
    ports:
      - '5432:5432'


  backend:
    container_name: backend
    build: ./backend/
    depends_on:
      - database
    ports:
      - '3000:3000'
    networks:
      web_pacani:
          ipv4_address: 172.20.0.10

  frontend:
    container_name: frontend
    build: ./frontend/
    depends_on:
      - backend
    networks:
      web_pacani:
          ipv4_address: 172.20.0.11
    ports:
      - '5176:5176'

networks:
  web_pacani:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
